#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar height=40 blur_radius=40 position=top sticky=on padding_left=12 padding_right=12 color=0x00000000 shadow=off

sketchybar --default \
  icon.font="Hack Nerd Font:Bold:14.0" \
  icon.color=$ITEM_COLOR \
  label.font="SF Pro:Regular:12.0" \
  label.color=$ITEM_COLOR \
  background.color=$ACCENT_COLOR \
  background.corner_radius=8 \
  background.height=28 \
  background.padding=2 \
  padding_left=6 \
  padding_right=6 \
  icon.padding_left=8 \
  icon.padding_right=6 \
  label.padding_left=4 \
  label.padding_right=8

source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/memory.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/calendar.sh

sketchybar --update
